// MakeNapoliGreen — Project Data
const projects = [
  {
    id: 'aiuola-bagnoli',
    title: 'Aiuola Bagnoli',
    titleEn: 'Bagnoli Flower Bed',
    city: 'Napoli',
    location: 'Bagnoli, Napoli',
    lat: 40.8176,
    lng: 14.1789,
    category: 'Aiuola',
    status: 'Attivo',
    description: 'Riqualificazione di uno spazio verde abbandonato nel quartiere Bagnoli. L\'obiettivo è restituire bellezza e vita a un\'area degradata, coinvolgendo i residenti nella cura e nella manutenzione del verde pubblico.',
    descriptionEn: 'Revitalisation of an abandoned green space in the Bagnoli neighbourhood. The goal is to restore beauty and life to a degraded area, involving residents in the care and maintenance of public greenery.',
    contributors: 8,
    img: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=640&q=80',
    tasks: ['Sopralluogo area', 'Raccolta fondi', 'Acquisto piante', 'Piantumazione'],
    updates: ['Giugno 2026: sopralluogo completato, area identificata e documentata.']
  },
  {
    id: 'orto-scampia',
    title: 'Orto Comunitario Scampia',
    titleEn: 'Scampia Community Garden',
    city: 'Napoli',
    location: 'Scampia, Napoli',
    lat: 40.8958,
    lng: 14.2258,
    category: 'Orto Urbano',
    status: 'Idea',
    description: 'Creare un orto condiviso nel parco di Scampia per coinvolgere i residenti nella coltivazione di ortaggi e piante aromatiche. Un luogo di aggregazione sociale e di educazione alimentare per famiglie e bambini.',
    descriptionEn: 'Create a shared garden in the Scampia park to engage local residents in growing vegetables and aromatic plants. A space for social gathering and food education for families and children.',
    contributors: 3,
    img: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=640&q=80',
    tasks: ['Trovare spazio disponibile', 'Contattare comune', 'Reclutare volontari'],
    updates: []
  },
  {
    id: 'pulizia-posillipo',
    title: 'Pulizia Spiaggia Posillipo',
    titleEn: 'Posillipo Beach Clean-up',
    city: 'Napoli',
    location: 'Posillipo, Napoli',
    lat: 40.7992,
    lng: 14.2007,
    category: 'Pulizia',
    status: 'Completato',
    description: 'Raccolta rifiuti sulla costa di Posillipo con la partecipazione attiva di cittadini e associazioni locali. Un\'azione concreta per proteggere il patrimonio naturale del Golfo di Napoli.',
    descriptionEn: 'Waste collection along the Posillipo coastline with the active participation of citizens and local associations. A concrete action to protect the natural heritage of the Gulf of Naples.',
    contributors: 24,
    img: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=640&q=80',
    tasks: ['Organizzare gruppi', 'Raccolta attrezzatura', 'Evento pulizia'],
    updates: ['Maggio 2026: completato con 24 volontari, raccolti 180 kg di rifiuti.']
  },
  {
    id: 'piantumazione-caserta',
    title: 'Alberatura Via Roma Caserta',
    titleEn: 'Tree Planting Via Roma Caserta',
    city: 'Caserta',
    location: 'Via Roma, Caserta',
    lat: 41.0726,
    lng: 14.3328,
    category: 'Piantumazione',
    status: 'Attivo',
    description: 'Piantare 30 alberi lungo Via Roma per ridurre le isole di calore urbano e migliorare la qualità dell\'aria nel centro di Caserta. Il progetto è sostenuto da una raccolta fondi comunitaria.',
    descriptionEn: 'Plant 30 trees along Via Roma to reduce urban heat islands and improve air quality in central Caserta. The project is supported by a community fundraiser.',
    contributors: 11,
    img: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=640&q=80',
    tasks: ['Permesso comunale', 'Acquisto alberi', 'Piantumazione'],
    updates: ['Luglio 2026: permesso richiesto al Comune di Caserta, in attesa di risposta.']
  },
  {
    id: 'giardino-salerno',
    title: 'Giardino Pensile Salerno',
    titleEn: 'Salerno Rooftop Garden',
    city: 'Salerno',
    location: 'Centro Storico, Salerno',
    lat: 40.6824,
    lng: 14.7681,
    category: 'Orto Urbano',
    status: 'Idea',
    description: 'Trasformare un tetto abbandonato nel centro storico di Salerno in un giardino condiviso. Il progetto prevede la collaborazione con il proprietario dell\'edificio e un gruppo di cittadini appassionati.',
    descriptionEn: 'Transform an abandoned rooftop in the historic centre of Salerno into a shared garden. The project involves collaboration with the building owner and a group of passionate citizens.',
    contributors: 5,
    img: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=640&q=80',
    tasks: ['Trovare proprietario', 'Progetto strutturale', 'Raccolta fondi'],
    updates: []
  },
  {
    id: 'aiuola-avellino',
    title: 'Rinverdimento Piazza Libertà',
    titleEn: 'Piazza Libertà Greening',
    city: 'Avellino',
    location: 'Piazza Libertà, Avellino',
    lat: 40.9143,
    lng: 14.7914,
    category: 'Aiuola',
    status: 'Attivo',
    description: 'Aggiungere verde e aiuole fiorite alla piazza principale di Avellino, rendendola un luogo più accogliente per residenti e turisti. Il progetto include la scelta di specie autoctone resistenti alla siccità.',
    descriptionEn: 'Add greenery and flower beds to Avellino main square, making it a more welcoming place for residents and tourists. The project includes the selection of native drought-resistant species.',
    contributors: 7,
    img: 'https://images.unsplash.com/photo-1477414348463-c0eb7f1359b6?w=640&q=80',
    tasks: ['Progetto paesaggistico', 'Raccolta fondi', 'Realizzazione'],
    updates: ['Giugno 2026: progetto paesaggistico approvato dalla comunità locale.']
  }
];
